language: cpp

os:
  - macos
  - linux

dist:
  - bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libzmq3-dev
      - protobuf-compiler
      - libprotobuf-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update                              ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install zeromq                      ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap jmuncaster/homebrew-header-only ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cppzmq                      ; fi

script:
  - mkdir build && cd build
  - cmake .. && make

notifications:
  email:
    recipients:
      - ccna.syl@gmail.com
    on_success: change
    on_failure: change
